using UnityEngine.InputSystem;

namespace VDPackages.InputManagementPackage.Enums
{
	/// <summary>
	/// InputActionMaps from the provided <see cref="InputActionAsset"/>, these are automatically generated by the <see cref="InputActionMapManager"/>
	/// </summary>
	public enum ControlType
	{
		Player,
		UI,
	}
}