using FMODUtilityPackage.Core;

namespace FMODUtilityPackage.Enums
{
	// ReSharper disable InconsistentNaming
	/// <summary>
	/// All FMOD events, these are automatically generated by the <see cref="AudioManager"/>
	/// </summary>
	public enum EventType // Automatically generated from FMOD events, do not edit! (Open the AudioManager inspector or use the "FMOD/Import Events" menu to regenerate)
	{
	}
}