using UnityEngine;
using VDPackages.FMODUtilityPackage.Core;
using VDPackages.FMODUtilityPackage.Structs;

namespace VDPackages.FMODUtilityPackage.Enums
{
	// ReSharper disable InconsistentNaming
	/// <summary>
	/// All FMOD events, these are automatically generated by the <see cref="AudioManager"/>
	/// </summary>
	public enum AudioEvent // Automatically generated from FMOD events, do not edit! (Open the AudioManager inspector or use the "FMOD/Import Events" menu to regenerate)
	{
		/// <FMODEventPath>
		/// event:/Ambient/BirdsAmbience
		/// </FMODEventPath>
		Ambient_BirdsAmbience,

		/// <FMODEventPath>
		/// event:/Ambient/Disaster/Rain&amp;WindBlowing
		/// </FMODEventPath>
		Ambient_Disaster_Rain_WindBlowing,

		/// <FMODEventPath>
		/// event:/Ambient/Disaster/WindBlowing
		/// </FMODEventPath>
		Ambient_Disaster_WindBlowing,

		/// <FMODEventPath>
		/// event:/Ambient/Disaster/HeavyRain
		/// </FMODEventPath>
		Ambient_Disaster_HeavyRain,

		/// <FMODEventPath>
		/// event:/Ambient/Disaster/Earthquake
		/// </FMODEventPath>
		Ambient_Disaster_Earthquake,

		/// <FMODEventPath>
		/// event:/Music/TitleMusic
		/// </FMODEventPath>
		Music_TitleMusic,

		/// <FMODEventPath>
		/// event:/Music/ItemStoreExit
		/// </FMODEventPath>
		Music_ItemStoreExit,

		/// <FMODEventPath>
		/// event:/Music/MenuMusic
		/// </FMODEventPath>
		Music_MenuMusic,

		/// <FMODEventPath>
		/// event:/Music/ItemStore
		/// </FMODEventPath>
		Music_ItemStore,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/KCAF
		/// </FMODEventPath>
		SFX_AudioResponse_KCAF,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/ClosingInventory
		/// </FMODEventPath>
		SFX_AudioResponse_ClosingInventory,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/PayingCoins
		/// </FMODEventPath>
		SFX_AudioResponse_PayingCoins,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/OpeningInventory
		/// </FMODEventPath>
		SFX_AudioResponse_OpeningInventory,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/HouseUpgrade
		/// </FMODEventPath>
		SFX_AudioResponse_HouseUpgrade,

		/// <FMODEventPath>
		/// event:/SFX/FoundationCrack
		/// </FMODEventPath>
		SFX_FoundationCrack,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/Click
		/// </FMODEventPath>
		SFX_AudioResponse_Click,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/MonsterFood
		/// </FMODEventPath>
		SFX_AudioResponse_MonsterFood,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/BuildingSoil
		/// </FMODEventPath>
		SFX_AudioResponse_BuildingSoil,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/Repairing
		/// </FMODEventPath>
		SFX_AudioResponse_Repairing,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/SelectingPlots
		/// </FMODEventPath>
		SFX_AudioResponse_SelectingPlots,

		/// <FMODEventPath>
		/// event:/SFX/CarEngine
		/// </FMODEventPath>
		SFX_CarEngine,

		/// <FMODEventPath>
		/// event:/NewsReport
		/// </FMODEventPath>
		NewsReport,

		/// <FMODEventPath>
		/// event:/SFX/HouseCrack
		/// </FMODEventPath>
		SFX_HouseCrack,

		/// <FMODEventPath>
		/// event:/SFX/QuakeMix
		/// </FMODEventPath>
		SFX_QuakeMix,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/BuildingFoundation
		/// </FMODEventPath>
		SFX_AudioResponse_BuildingFoundation,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/Breaking
		/// </FMODEventPath>
		SFX_AudioResponse_Breaking,

		/// <FMODEventPath>
		/// event:/SFX/MonsterGrowl
		/// </FMODEventPath>
		SFX_MonsterGrowl,

		/// <FMODEventPath>
		/// event:/SFX/ThunderMix
		/// </FMODEventPath>
		SFX_ThunderMix,

		/// <FMODEventPath>
		/// event:/SFX/AchievementUnlocked
		/// </FMODEventPath>
		SFX_AchievementUnlocked,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/TimeFreeze
		/// </FMODEventPath>
		SFX_AudioResponse_TimeFreeze,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/CollectingRent
		/// </FMODEventPath>
		SFX_AudioResponse_CollectingRent,

		/// <FMODEventPath>
		/// event:/SFX/SoilSinking
		/// </FMODEventPath>
		SFX_SoilSinking,

		/// <FMODEventPath>
		/// event:/SFX/AudioResponse/BuildingHouse
		/// </FMODEventPath>
		SFX_AudioResponse_BuildingHouse,

		/// <FMODEventPath>
		/// event:/SFX/MonsterEating
		/// </FMODEventPath>
		SFX_MonsterEating,
	}

	/// <summary>
	/// Provides extension functions for <see cref="AudioEvent"/> to simplify playing an event
	/// </summary>
	public static class AudioEventExtensions
	{
		/// <inheritdoc cref="AudioPlayer.PlayOneShot2D(AudioEvent)"/>
		public static void PlayOneShot2D(this AudioEvent audioEvent)
		{
			AudioPlayer.PlayOneShot2D(audioEvent);
		}
		
		/// <inheritdoc cref="AudioPlayer.PlayOneShot2D(AudioEvent, EventParameters)"/>
		public static void PlayOneShot2D(this AudioEvent audioEvent, EventParameters parameters)
		{
			AudioPlayer.PlayOneShot2D(audioEvent, parameters);
		}
		
		/// <inheritdoc cref="AudioPlayer.PlayOneShot3D(AudioEvent)"/>
		public static void PlayOneShot3D(this AudioEvent audioEvent)
		{
			AudioPlayer.PlayOneShot3D(audioEvent);
		}
		
		/// <inheritdoc cref="AudioPlayer.PlayOneShot3D(AudioEvent, GameObject)"/>
		public static void PlayOneShot3D(this AudioEvent audioEvent, GameObject location)
		{
			AudioPlayer.PlayOneShot3D(audioEvent, location);
		}
		
		/// <inheritdoc cref="AudioPlayer.PlayOneShot3D(AudioEvent, EventParameters, GameObject)"/>
		public static void PlayOneShot3D(this AudioEvent audioEvent, EventParameters parameters, GameObject location)
		{
			AudioPlayer.PlayOneShot3D(audioEvent, parameters, location);
		}
	}
}